POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "xyz",
    "password": "123456",
    "email" : "zyx@123.com"
}
 
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "zyx@123.com",
    "password": "123456"
}

###
GET http://localhost:5000/api/notifications
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWE0ZDVmZjU2MWYxZjhmMTYwMmQyNCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQzNDkxNjczLCJleHAiOjE3NDQwOTY0NzN9.7_wYz2N6RSfzM8ryP_6LzqGVVR-kFv30-Ou4x4Qhbig

###
POST http://localhost:5000/api/notifications/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2QzYWJkNmVkOTcwNTJjMDRmNGE3OSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzQyNzIyNSwiZXhwIjoxNzQ0MDMyMDI1fQ.t-bLU3tDNryXva3VoPDc1oTptNhMf6Xm3rOc6rUrAiI

{
  "type": "announcement",
  "message": "We have just updated our platform with new features!"
}

###
POST http://localhost:5000/api/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2QzYWJkNmVkOTcwNTJjMDRmNGE3OSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzM0OTU5NCwiZXhwIjoxNzQzOTU0Mzk0fQ.iYckj8OFPLJj22OQbsSM8aeNb-T6d2uk0D5_DcrZcjQ

{
   "receiverId": "67e254dd94f3c746a588d011", 
   "content": "i'm abc"
}

###
GET http://localhost:5000/api/messages/67e254dd94f3c746a588d011
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2QzYWJkNmVkOTcwNTJjMDRmNGE3OSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzM0OTU5NCwiZXhwIjoxNzQzOTU0Mzk0fQ.iYckj8OFPLJj22OQbsSM8aeNb-T6d2uk0D5_DcrZcjQ

###
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTI1NGRkOTRmM2M3NDZhNTg4ZDAxMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzgzODYwNywiZXhwIjoxNzQ0NDQzNDA3fQ.PU_R7d7NZWxvg-7_4yA3UVwAm4R-MFpY0OnI4cCUBsU


###
PUT http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2QzYWJkNmVkOTcwNTJjMDRmNGE3OSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzMxMjI3OSwiZXhwIjoxNzQzOTE3MDc5fQ.ET0wC9LVto-0jSWyzNqlTg0O4v-_fPE5BTBcvzHYlRs

{
    "displayName": "abc999@123.com"
}

###
GET http://localhost:5000/api/posts/user/67ea4d5ff561f1f8f1602d24
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2QzYWJkNmVkOTcwNTJjMDRmNGE3OSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzQ5MzExMywiZXhwIjoxNzQ0MDk3OTEzfQ.TqzJFhy2kCpqSPSO7dtX8tnBhdGjgEs2vsv_2Jx5N_Y
###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTI1NGRkOTRmM2M3NDZhNTg4ZDAxMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzgzNjcxMCwiZXhwIjoxNzQ0NDQxNTEwfQ.8XlwTVirQzBL1mShnmFMzpLW5qfWqrrRvk3TaAX0geo

{
    "content": "This post has mention",
    "tags": ["#img"],
    "mentions": ["67ea9eabe2fcce3ffa4c02bd"],
    "visibility": "public"
}

###
GET http://localhost:5000/api/posts/search?query=img
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTI1NGRkOTRmM2M3NDZhNTg4ZDAxMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzkwMTgyNCwiZXhwIjoxNzQ0NTA2NjI0fQ.cV4zI2nRSzCPs41rfYB-EKL8HwZOPv5Vm7cRGPXA43g


###
GET http://localhost:5000/api/users/friends
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjIxMzg4NDA5MzU2ZGMxY2NjYzUxMSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQzOTE3OTk3LCJleHAiOjE3NDQ1MjI3OTd9._SoP86PnrBOxU1ZNZRAh01cOBuBodPkdEKKg4BXJApQ


###
POST  http://localhost:5000/api/users/friends/67ea9b11995e847155c738ca
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWE5YzIwZTJmY2NlM2ZmYTRjMDJiYSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQzNDkwODQ1LCJleHAiOjE3NDQwOTU2NDV9.K5klQStcGAaBm53QUY6xEEeX8E3to4k0ZZijDTnIoIo

###
POST  http://localhost:5000/api/users/follow/67f21388409356dc1cccc511
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjIxMzlhNDA5MzU2ZGMxY2NjYzUxNCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQzOTE4NDkwLCJleHAiOjE3NDQ1MjMyOTB9.0eBV683B3z16o1aZg3w-TSuqyAZNWytpGFydLnm81ZI
# 67ebb3a7e3ca5bc7f5196305

# 67eb9f30909b022a15ea071b

###
GET http://localhost:5000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjIxMzlhNDA5MzU2ZGMxY2NjYzUxNCIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQzOTE4ODc1LCJleHAiOjE3NDQ1MjM2NzV9.MfSlSWs_zVWzwdx_h7js5vqvVhTRA69wpYhPm3Yd2l4


###
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTI1NGRkOTRmM2M3NDZhNTg4ZDAxMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0Mzg0MDk3MSwiZXhwIjoxNzQ0NDQ1NzcxfQ.DmBCsoERwrh9Ki2clfLKjMNhliOXK6mpCDiKdxxKiQw


###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzQyMzBmZGU3NTBjNjg0NDQ4YmUzZmUiLCJpYXQiOjE2NjUyODQ2Mzh9.jQ7426OnoMRBEgmykigALosgiJuyxiyf_gJ7om4aHFE
###
GET http://localhost:5000/api/posts/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2QzYWJkNmVkOTcwNTJjMDRmNGE3OSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzMxNDI4NywiZXhwIjoxNzQzOTE5MDg3fQ.lzaBnpmt_O6wFXZcETDxY__vJGwjLr8S3te-KuAawks

###
GET http://localhost:5000/api/posts/67e24bbf98c9c63d86a7e030
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2QzYWJkNmVkOTcwNTJjMDRmNGE3OSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQyODg1MzcxLCJleHAiOjE3NDM0OTAxNzF9.wvcgF5z-OBSxxfsRGFPsO3bOsaay967zmlQhZoj14tE

###
GET http://localhost:5000/api/posts/top-tags
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2QzYWJkNmVkOTcwNTJjMDRmNGE3OSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQzMzAyMDM4LCJleHAiOjE3NDM5MDY4Mzh9.BAcpWsnSRbvZBIehNl6PyHmTNpX_o9HPzwnsXodVyIc


###
PUT  http://localhost:5000/api/posts/63423a4628bc36969000c70f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzQwZjliYmNmMjRhMjBiYzVmZGZlMjEiLCJpYXQiOjE2NjUyODI1OTl9.qxRetDfKeL_yhUQ81H-w4MVBkHLgqSjtD-3-2mbbZFk

{
    "title":"Vue",
    "description":"vueeee",
    "url": "vue.org",
    "status": "LEARNING"
}

###
DELETE http://localhost:5000/api/posts/67e24bbf98c9c63d86a7e030
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTI1NGRkOTRmM2M3NDZhNTg4ZDAxMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0MzMwMzIyOCwiZXhwIjoxNzQzOTA4MDI4fQ.VxgQMJ2CVzp1b5JvV0JY7oo03Bzqd6SBQBYLdzvAJFw

###
POST http://localhost:5000/api/posts/67e8b5f2cf6df59b7531f4f6/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTI1NGM1OTRmM2M3NDZhNTg4ZDAwYyIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQzMzA3MDg5LCJleHAiOjE3NDM5MTE4ODl9.VeHDiDTbWfliQJYLjae49VRhEvtz0-VIEqrCPf8APYw

###
POST http://localhost:5000/api/posts/67e8b5f2cf6df59b7531f4f6/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Y2QzYWJkNmVkOTcwNTJjMDRmNGE3OSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzQzMzAyMDM4LCJleHAiOjE3NDM5MDY4Mzh9.BAcpWsnSRbvZBIehNl6PyHmTNpX_o9HPzwnsXodVyIc

{
    "text": "This is a comment"
}

